apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 185545846425/nodejsapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    run: node-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: nodejs
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: deployment-nodejs
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60