apiVersion: v1
kind: Pod
metadata:
  name: simple-example-volume-pod
spec:
  containers:
    - name: writer
      image: debian:buster-slim
      command:
      - /bin/bash
      - -c
      - while true; do sleep 10; echo "hello" >> /test-volume/output.txt; done
      volumeMounts:
        - mountPath: /test-volume
          name: test-volume
    - name: reader
      image: debian:buster-slim
      command:
      - /bin/bash
      - -c
      - while true; do sleep 10; cat /test-volume/output.txt; done
      volumeMounts:
      - mountPath: /test-volume
        name: test-volume
  volumes:
    - name: test-volume
      # emptyDir: {}