apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitor
  namespace: default
subjects:
- kind: ServiceAccount
  name: example-sa
roleRef:
  kind: Role
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io