apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer  
  ports:
    - port: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30010
  selector:
    app: web
  externalIPs:
  - 192.168.49.2
